apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angulartest-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angulartest
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: angulartest
    spec: 
      containers: 
      - name: angulartest 
        image: acrimage.azurecr.io/angular-app:#{Build.BuildId}#
        ports: 
        - containerPort: 80 
## test2        
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angulartest-service 
spec: 
  selector: 
    app: angulartest 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
  type: LoadBalancer 
